### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by montanaflynn** [russross/meddler#15]
Hi, I'm using meddler and love it! However I have noticed that it logs[1] warnings if there is a field not found in the struct. I found the Debug var is set to true in scan.go on line #54[2] could this be somehow configured by the user?

1:
```
2015/12/01 13:07:18 meddler.Targets: column [updated_at] not found in struct
2015/12/01 13:07:18 meddler.WriteTargets: column [updated_at] not found in struct
```

2: https://github.com/russross/meddler/blob/f742b0f9424f3bfaffe189e921d734608929e84f/scan.go#L54

**Comment by russross** [comment]
You can just write:

meddler.Debug = false

before using any meddler functions to turn it off.

**Comment by montanaflynn** [comment]
Thanks!
