### ISSUE TITLE
Update go-sqlite3 version to ommit warnings

### ISSUE THREAD

**Issue by edo1** [russross/meddler#26]
There is a slight incompatibility between sqlite3 prior to 3.33 and gcc 10, more details here:
https://github.com/mattn/go-sqlite3/issues/803
https://sqlite.org/forum/forumpost/e39020f82d7d510ea4d4a08ae370ca8df061c8b91884c82fda4897853faa2096

This is fixed in sqlite release 3.33.0:
https://www.sqlite.org/src/info/04e1edd8e5821a37

Sqlite release 3.33+ is used in the go-sqlite3 1.14.1 and later:
https://github.com/mattn/go-sqlite3/compare/v1.14.0...v1.14.1
(yes, latest version of go-sqlte3 is 1.14.x, not 2.0.x)

So please update the sqlite version in the go.mod file to 1.14.1 or later (I suggest using the current version 1.14.7).

**Comment by russross** [comment]
Updated. Thanks for the report and the suggested fix!
